### ISSUE TITLE
100% CPU usage

### ISSUE THREAD

**Issue by Ubuntuworld** [nikeee/TeamSpeak3QueryAPI#39] opened 2019-04-07 17:04 UTC
After 5minutes after connecting to my teamspeak server, my software uses 100% of CPU without calling any function or executing any loop.

**Comment by nikeee** [comment] 2019-04-07 18:23
Can you provide the code you used?

**Comment by Ubuntuworld** [comment] 2019-04-09 07:53
`tsclient = new TeamSpeakClient(cfg.IP, cfg.Port);
            tsquery = new QueryClient(cfg.IP, cfg.Port);
            try
            {
                await tsclient.Connect();
                await tsclient.Login(cfg.Username, cfg.Password);
                await tsquery.Connect();
            }
            catch (Exception)
            {
                await this.ShowMessageAsync("Could not connect to TS server!", "Make sure, that you have a valid connection configured");
            }`

**Comment by Ubuntuworld** [comment] 2019-04-09 07:54
```csharp
tsclient = new TeamSpeakClient(cfg.IP, cfg.Port);
            tsquery = new QueryClient(cfg.IP, cfg.Port);
            try
            {
                await tsclient.Connect();
                await tsclient.Login(cfg.Username, cfg.Password);
                await tsquery.Connect();
            }
            catch (Exception)
            {
                await this.ShowMessageAsync("Could not connect to TS server!", "Make sure, that you have a valid connection configured");
            }
```

**Comment by nikeee** [comment] 2019-04-09 07:59
Though I don't think it a problem, but is there any reason why you use two clients?

**Comment by Ubuntuworld** [comment] 2019-04-09 08:07
Because i dont see a possibility to send a custom command with the TeamSpeakClient

**Comment by Ubuntuworld** [comment] 2019-04-09 08:18
Ive tryed to use the TeamspeakClient only and now my cpu usage looks like this after a few minutes.

![CPU](https://user-images.githubusercontent.com/8238338/55784416-d2451f00-5ab0-11e9-9d3c-5ed1f97d138a.JPG)

**Comment by MaximilianAst** [comment] 2019-04-09 08:30
> Because i dont see a possibility to send a custom command with the TeamSpeakClient

It won't fix the problem I think, but it'll make the code cleaner. There is public a property in `TeamSpeakClient` on which you can access the underlying `QueryClient`. So there's no need to connect an additional `QueryClient` for this usecase.

    public QueryClient Client { get; }

**Comment by Ubuntuworld** [comment] 2019-04-09 08:41
That improves the code, but doesent solve my problem. ;)

**Comment by MaximilianAst** [comment] 2019-04-09 08:49
I have to look into it the evening. Or nikeee is faster. :)

**Comment by MaximilianAst** [comment] 2019-04-09 19:08
I had it running for 18 minutes and still no cpu load. At least in a cmd application. Which framework are you using? Also tried it with a winform application and`net462` (about 8 mins). So with my current setup its hard to reporduce. Could you use the CPU profiler and tell us which module is using so much CPU time to narrow the problem down?

![image](https://user-images.githubusercontent.com/13467300/55827376-5677c080-5b0a-11e9-94f1-a057e2515023.png)

**Comment by Ubuntuworld** [comment] 2019-04-10 12:07
I cant load the part, where the CPU useage is that extreme. Its really confusing.

![Here it works](https://user-images.githubusercontent.com/8238338/55877267-e6b11680-5b99-11e9-8cf5-7b0c547f7a2f.PNG)
Here it works

![And here its loading the whole time](https://user-images.githubusercontent.com/8238338/55877277-edd82480-5b99-11e9-95b5-634971f291a6.PNG)
Here it loads the whole time

**Comment by nikeee** [comment] 2019-04-10 13:51
Yould you provide a minimum reproduction of the problem?

**Comment by Ubuntuworld** [comment] 2019-04-10 14:01
Of course. Ill will write this evening i Dont have much time at the Moment.

**Comment by Ubuntuworld** [comment] 2019-04-10 15:29
I maybe found the problem:
Im connecting to a TS3 server in a VM. I dont know why this should be the problem, but it looks like it is. When im trying to connect to a local instance on my windows system, it works perfectly fine. Im going to provide you my files anyway later, if you want.

**Comment by Ubuntuworld** [comment] 2019-04-11 06:53
Please try it with Ubuntu 18.04 as server OS. Make sure, its in a vm or a remote server. The problem with the cpu load also happens, when the server stops. So im very sure, that happens with a timeout after 5minutes.

**Comment by Ubuntuworld** [comment] 2019-04-11 14:43
[Teamspeak-query-cpu-problem.zip](https://github.com/nikeee/TeamSpeak3QueryAPI/files/3069199/Teamspeak-query-cpu-problem.zip)

You need to install the missing packages, because else it would be to big for github.

**Comment by nikeee** [comment] 2019-04-11 14:58
I cannot run the code atm, but does this code also run into this error? I'm asking because this is a WinForms application. The screenshots you posted originate from a WPF application, I think.

Also, you should await all calls to functions returning Tasks (Login, connect, etc in this case).

**Comment by Ubuntuworld** [comment] 2019-04-11 15:02
Im using await in my software normally. This software i have sended you have the same problems. You are true the software im working on is wirtten with WPF and this is WinForms, but they have the same problem.   Please try it with a linux server in a VM or as a remote linux server.

**Comment by Ubuntuworld** [comment] 2019-04-17 18:37
Okay. Im going to change to the "official" Teamspeak API

**Comment by nikeee** [comment] 2019-04-17 20:25
I'm sorry that I don't have any spare time to have a deep look at this. We're doing this in our free time.

Out of curiosity: what official API are going to use?

**Comment by Ubuntuworld** [comment] 2019-04-19 09:21
I understand that. And that was a misinformation from my side. There is no teamspeak3 query c# api. Im sorry. But im unable to fix this problem from my side, so i think im going to cancel this project until you had time. Tell me if you need more information from my side.

**Comment by nikeee** [comment] 2019-04-19 12:30
Feel free to debug this library as you like. I mean, it's open source.

**Comment by Splamy** [comment] 2019-04-19 14:59
@Ubuntuworld I usually don't like advertising my own projects on other projects, but if you want a temporary solution until nikeee has time to fix you can try out the [ts3client](https://github.com/Splamy/TS3AudioBot) I haven't mananged to separate the ts3audiobot and and the ts3client repo into two projects on github, but the ts3client csproj can be used standalone. It can connect as query or full client. The documentation is just a bit bad and it does not use async.

**Comment by Ubuntuworld** [comment] 2019-04-19 15:03
@Splamy Thanks for you help, im going to look at it, but the async methods are really great...
@nikeee Im going to try, but i dont now if i have the knowledge for that.

**Comment by Ubuntuworld** [comment] 2019-04-19 19:17
Found the problem.
When ther server closes the connection, the api is in an endless loop:

´´´´csharp
while (!_cancelTask)
                {
                    var line = await _reader.ReadLineAsync().ConfigureAwait(false);
                    Debug.WriteLine(line);
                    if (string.IsNullOrWhiteSpace(line))
                        continue;
´´´´
File: QueryClient.cs
Line: 339

**Comment by Ubuntuworld** [comment] 2019-04-19 19:27
````csharp
                while (!_cancelTask)
                {
                    var line = await _reader.ReadLineAsync().ConfigureAwait(false);
                    Debug.WriteLine(line);
                    if(line == null)
                    {
                        IsConnected = false;
                        _cancelTask = true;
                    }
                    if (string.IsNullOrWhiteSpace(line))
                        continue;
````

It looks like, this is going to work for me. But i think it needs further testing or optimisation from your side. I dont know the whole project :)

**Comment by nikeee** [comment] 2019-04-19 19:30
Cool! I think the real fix would involve more code. Currently, we also lack the ability to use a CancellationToken, I think.

**Comment by Ubuntuworld** [comment] 2019-04-19 19:32
Ive never used a CancellationToken ^^
If i can help you more, just tell me.
Thanks for your work on this api anyway

**Comment by nikeee** [comment] 2019-04-19 21:32
I added experimental CTS support in 6a776cf8c014303cf32172836f63784ee831ecb8 and 30ebc0f32e472a4e93cd5288e699241665668203. It may also fix this bug. Haven tested the change.

Also, there is now a method to disconnect form the server.

Could you check if the issue still persists and report back?

**Comment by Ubuntuworld** [comment] 2019-04-20 06:02
Yes it works. There is no high cpu load anymore

**Closed** 2019-04-20 06:30 UTC
Labels: bug

**Comment by Ubuntuworld** [comment] 2019-04-20 07:33
When are you going to implement this outside of the beta?

**Comment by nikeee** [comment] 2019-04-20 08:22
I just have to tag this release. Before doing that, I'd like to be sure that it does not break anything.
